name = "onyu theme"
license = "MIT"
licenselink = "https://github.com/fermarval/onyu-website/blob/master/LICENSE"
description = "onyu theme"
homepage = "https://onyu.net"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.54"

[author]
  name = "fermarval"
  homepage = "https://onyu.net/"