# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Rappo"
license = "MIT"
licenselink = "https://github.com/fermarval/hugo-theme-rappo/blob/master/LICENSE.md"
description = "Rappo theme by Themefisher ported to Hugo by Fermarval"
homepage = "https://github.com/saey55/hugo-theme-rappo/"
tags = ["Rappo", "Hugo", "parallax"]
features = ["", "", ""]
min_version = 0.17

[author]
  name = "Dreambuzz (Port by Fermarval)"
  homepage = "https://marmolejo.me"

[original]
  name = "Rappo"
  homepage = "https://themefisher.com/products/rappo-corporate-template/"